import type { RateCurrency } from '@payscope/shared';

export const DEFAULT_SEED = 20260630;
export const DEFAULT_EMPLOYEE_COUNT = 10_000;
export const EMAIL_DOMAIN = 'acme.example';
// Fixed, not Date.now(): output stays identical between runs and is never "in the future".
export const REFERENCE_DATE = new Date('2026-06-30T00:00:00.000Z');
export const EARLIEST_HIRE_DATE = new Date('2010-01-04T00:00:00.000Z');

export type NameRegion = 'anglo' | 'german' | 'french' | 'indian' | 'japanese' | 'brazilian';

export interface SeedCountry {
  code: string;
  currency: RateCurrency;
  region: NameRegion;
  /** Relative pay level vs. the US band. */
  costFactor: number;
  /** Share of headcount (relative). */
  weight: number;
}

export const COUNTRIES: readonly SeedCountry[] = [
  { code: 'US', currency: 'USD', region: 'anglo', costFactor: 1.0, weight: 28 },
  { code: 'GB', currency: 'GBP', region: 'anglo', costFactor: 0.75, weight: 12 },
  { code: 'DE', currency: 'EUR', region: 'german', costFactor: 0.8, weight: 12 },
  { code: 'FR', currency: 'EUR', region: 'french', costFactor: 0.72, weight: 8 },
  { code: 'IN', currency: 'INR', region: 'indian', costFactor: 0.28, weight: 16 },
  { code: 'JP', currency: 'JPY', region: 'japanese', costFactor: 0.7, weight: 6 },
  { code: 'BR', currency: 'BRL', region: 'brazilian', costFactor: 0.35, weight: 6 },
  { code: 'CA', currency: 'CAD', region: 'anglo', costFactor: 0.85, weight: 7 },
  { code: 'AU', currency: 'AUD', region: 'anglo', costFactor: 0.9, weight: 5 },
];

export interface SeedJobTitle {
  title: string;
  department: string;
  /** Annual pay band in whole USD before country and currency adjustment. */
  minUsd: number;
  maxUsd: number;
  weight: number;
  internEligible: boolean;
}

export const JOB_TITLES: readonly SeedJobTitle[] = [
  {
    title: 'Software Engineer',
    department: 'Engineering',
    minUsd: 70_000,
    maxUsd: 140_000,
    weight: 18,
    internEligible: true,
  },
  {
    title: 'Senior Software Engineer',
    department: 'Engineering',
    minUsd: 110_000,
    maxUsd: 190_000,
    weight: 9,
    internEligible: false,
  },
  {
    title: 'Engineering Manager',
    department: 'Engineering',
    minUsd: 140_000,
    maxUsd: 230_000,
    weight: 3,
    internEligible: false,
  },
  {
    title: 'QA Engineer',
    department: 'Engineering',
    minUsd: 55_000,
    maxUsd: 105_000,
    weight: 6,
    internEligible: true,
  },
  {
    title: 'DevOps Engineer',
    department: 'Engineering',
    minUsd: 80_000,
    maxUsd: 150_000,
    weight: 5,
    internEligible: false,
  },
  {
    title: 'Data Scientist',
    department: 'Data',
    minUsd: 85_000,
    maxUsd: 165_000,
    weight: 5,
    internEligible: true,
  },
  {
    title: 'Product Manager',
    department: 'Product',
    minUsd: 95_000,
    maxUsd: 180_000,
    weight: 5,
    internEligible: false,
  },
  {
    title: 'UX Designer',
    department: 'Design',
    minUsd: 65_000,
    maxUsd: 120_000,
    weight: 4,
    internEligible: true,
  },
  {
    title: 'Sales Representative',
    department: 'Sales',
    minUsd: 45_000,
    maxUsd: 95_000,
    weight: 10,
    internEligible: true,
  },
  {
    title: 'Account Executive',
    department: 'Sales',
    minUsd: 70_000,
    maxUsd: 150_000,
    weight: 6,
    internEligible: false,
  },
  {
    title: 'Sales Manager',
    department: 'Sales',
    minUsd: 100_000,
    maxUsd: 180_000,
    weight: 2,
    internEligible: false,
  },
  {
    title: 'Marketing Specialist',
    department: 'Marketing',
    minUsd: 50_000,
    maxUsd: 95_000,
    weight: 5,
    internEligible: true,
  },
  {
    title: 'Financial Analyst',
    department: 'Finance',
    minUsd: 60_000,
    maxUsd: 110_000,
    weight: 4,
    internEligible: true,
  },
  {
    title: 'Accountant',
    department: 'Finance',
    minUsd: 50_000,
    maxUsd: 95_000,
    weight: 3,
    internEligible: false,
  },
  {
    title: 'HR Business Partner',
    department: 'People',
    minUsd: 60_000,
    maxUsd: 115_000,
    weight: 3,
    internEligible: false,
  },
  {
    title: 'Recruiter',
    department: 'People',
    minUsd: 50_000,
    maxUsd: 95_000,
    weight: 3,
    internEligible: true,
  },
  {
    title: 'Operations Manager',
    department: 'Operations',
    minUsd: 80_000,
    maxUsd: 150_000,
    weight: 3,
    internEligible: false,
  },
  {
    title: 'Customer Support Specialist',
    department: 'Support',
    minUsd: 35_000,
    maxUsd: 65_000,
    weight: 6,
    internEligible: true,
  },
];

export type EmploymentTypeValue = 'FULL_TIME' | 'PART_TIME' | 'CONTRACT' | 'INTERN';

export const EMPLOYMENT_TYPES: readonly {
  value: EmploymentTypeValue;
  weight: number;
  payFactor: number;
}[] = [
  { value: 'FULL_TIME', weight: 80, payFactor: 1 },
  { value: 'PART_TIME', weight: 8, payFactor: 0.6 },
  { value: 'CONTRACT', weight: 9, payFactor: 1.1 },
  { value: 'INTERN', weight: 3, payFactor: 0.35 },
];

export interface NamePool {
  first: readonly string[];
  last: readonly string[];
}

export const NAME_POOLS: Record<NameRegion, NamePool> = {
  anglo: {
    first: [
      'James',
      'Emma',
      'Oliver',
      'Sophia',
      'Liam',
      'Ava',
      'Noah',
      'Isabella',
      'William',
      'Mia',
      'Benjamin',
      'Charlotte',
      'Lucas',
      'Amelia',
      'Henry',
      'Grace',
      'Jack',
      'Chloe',
      'Daniel',
      'Hannah',
    ],
    last: [
      'Smith',
      'Johnson',
      'Williams',
      'Brown',
      'Jones',
      'Taylor',
      'Davies',
      'Wilson',
      'Evans',
      'Thomas',
      'Walker',
      'Roberts',
      'Green',
      'Hall',
      'Wright',
      'Clarke',
      'Turner',
      'Hughes',
      'Carter',
      'Murphy',
    ],
  },
  german: {
    first: [
      'Lukas',
      'Anna',
      'Felix',
      'Lena',
      'Jonas',
      'Marie',
      'Maximilian',
      'Sophie',
      'Paul',
      'Laura',
      'Leon',
      'Julia',
      'Tim',
      'Katharina',
      'Jan',
      'Lea',
      'Moritz',
      'Johanna',
      'Stefan',
      'Greta',
    ],
    last: [
      'Müller',
      'Schmidt',
      'Schneider',
      'Fischer',
      'Weber',
      'Meyer',
      'Wagner',
      'Becker',
      'Schulz',
      'Hoffmann',
      'Koch',
      'Richter',
      'Klein',
      'Wolf',
      'Schröder',
      'Neumann',
      'Braun',
      'Krüger',
      'Hartmann',
      'Lange',
    ],
  },
  french: {
    first: [
      'Louis',
      'Camille',
      'Hugo',
      'Léa',
      'Jules',
      'Manon',
      'Arthur',
      'Chloé',
      'Gabriel',
      'Inès',
      'Théo',
      'Emma',
      'Raphaël',
      'Zoé',
      'Antoine',
      'Clara',
      'Nathan',
      'Juliette',
      'Mathieu',
      'Élise',
    ],
    last: [
      'Martin',
      'Bernard',
      'Dubois',
      'Thomas',
      'Robert',
      'Richard',
      'Petit',
      'Durand',
      'Leroy',
      'Moreau',
      'Simon',
      'Laurent',
      'Lefebvre',
      'Michel',
      'Garcia',
      'David',
      'Bertrand',
      'Roux',
      'Vincent',
      'Fournier',
    ],
  },
  indian: {
    first: [
      'Aarav',
      'Priya',
      'Vivaan',
      'Ananya',
      'Arjun',
      'Diya',
      'Rohan',
      'Isha',
      'Kabir',
      'Meera',
      'Aditya',
      'Sneha',
      'Rahul',
      'Kavya',
      'Vikram',
      'Neha',
      'Sanjay',
      'Pooja',
      'Karan',
      'Riya',
    ],
    last: [
      'Sharma',
      'Patel',
      'Singh',
      'Kumar',
      'Gupta',
      'Reddy',
      'Iyer',
      'Nair',
      'Mehta',
      'Joshi',
      'Desai',
      'Rao',
      'Chopra',
      'Malhotra',
      'Bose',
      'Agarwal',
      'Kapoor',
      'Verma',
      'Menon',
      'Banerjee',
    ],
  },
  japanese: {
    first: [
      'Haruto',
      'Yui',
      'Sota',
      'Hina',
      'Ren',
      'Aoi',
      'Kenji',
      'Sakura',
      'Takumi',
      'Mio',
      'Daiki',
      'Yuna',
      'Hiroshi',
      'Emi',
      'Yuki',
      'Akari',
      'Shota',
      'Nanami',
      'Kaito',
      'Rina',
    ],
    last: [
      'Sato',
      'Suzuki',
      'Takahashi',
      'Tanaka',
      'Watanabe',
      'Ito',
      'Yamamoto',
      'Nakamura',
      'Kobayashi',
      'Kato',
      'Yoshida',
      'Yamada',
      'Sasaki',
      'Matsumoto',
      'Inoue',
      'Kimura',
      'Hayashi',
      'Shimizu',
      'Mori',
      'Ikeda',
    ],
  },
  brazilian: {
    first: [
      'Miguel',
      'Helena',
      'Arthur',
      'Alice',
      'Heitor',
      'Laura',
      'Davi',
      'Valentina',
      'Gabriel',
      'Sofia',
      'Bernardo',
      'Júlia',
      'Rafael',
      'Beatriz',
      'Lucas',
      'Larissa',
      'Pedro',
      'Camila',
      'Thiago',
      'Fernanda',
    ],
    last: [
      'Silva',
      'Santos',
      'Oliveira',
      'Souza',
      'Rodrigues',
      'Ferreira',
      'Alves',
      'Pereira',
      'Lima',
      'Gomes',
      'Costa',
      'Ribeiro',
      'Martins',
      'Carvalho',
      'Almeida',
      'Lopes',
      'Soares',
      'Fernandes',
      'Vieira',
      'Barbosa',
    ],
  },
};
